### ISSUE TITLE
(Installation) Error: Could not create the Java Virtual Machine

### ISSUE THREAD

**Issue by BonKirill** [dsukhoroslov/bagri#149]
This error occurs while trying to run bgcache.cmd or bgadmin.cmd
![screenshot](https://user-images.githubusercontent.com/35528572/35297625-9e2ea158-0090-11e8-98c7-a3e403f9e3d3.png)

**Comment by dsukhoroslov** [comment]
removed obsolete (logging) JVM options, but the app still cannot start because of classes not found error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3139)
```
- decided to fix documentation (only Java v 6..8 supported) for the release 1.2.0; 
- will provide java v9 compatible build in the next major release (Bagri 2.0.0);
